### ISSUE TITLE
Unable to initialize gitcc

### ISSUE THREAD

**Issue by abubakarmkarajagi** [charleso/git-cc#101]
I am unable to initialize gitcc. Please refer below error. Could please assist 
C:\Users\User>gitcc init C:/Users/User/User_CCC_git
Traceback (most recent call last):
  File "C:\Program Files\Python311\Scripts\gitcc-script.py", line 33, in <module>
    sys.exit(load_entry_point('git-cc==1.0.1.dev0', 'console_scripts', 'gitcc')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\git_cc-1.0.1.dev0-py3.11.egg\git_cc\gitcc.py", line 25, in main
  File "C:\Program Files\Python311\Lib\site-packages\git_cc-1.0.1.dev0-py3.11.egg\git_cc\gitcc.py", line 30, in invoke
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?

**Comment by charleso** [comment]
I'm really sorry. This package is not really supported. It looks like we probably need to upgrade gitcc to support Python 3.11 but I'm afraid I'm unable to help with that. I just want to set expectations now so you don't waste your time. :(

**Comment by abubakarmkarajagi** [comment]
Hello Charleso ,

I installed  2.7.9 version of Python .I was able to eliminate that error.
Now I am getting below error.

$ gitcc rebase
No 'clearcase' variable found for branch 'master'


I want to rebase on main without any branches.I am using base clearcase.

This is my gitcc.file content

[core]
include = Import
exclude = lost+found
ignore_private_files = False
debug = False
type = Clearcase
[master]
clearcase = C:\Users\E9951943\E9951943_CC_Git\vobs\sandbox
branches = main

But still the issue persists. Please assist.

Regards,
Abubakar.M.K

From: charleso ***@***.***>
Sent: Tuesday, February 21, 2023 4:05 PM
To: charleso/git-cc ***@***.***>
Cc: Karajagi, Abubakar ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [charleso/git-cc] Unable to initialize gitcc (Issue #101)


I'm really sorry. This package is not really supported. It looks like we probably need to upgrade gitcc to support Python 3.11 but I'm afraid I'm unable to help with that. I just want to set expectations now so you don't waste your time. :(

**Comment by abubakarmkarajagi** [comment]
Hello Charleso ,

Did you get a chance to look into below request ?

Regards,
Abubakar.M.K
From: Karajagi, Abubakar
Sent: Tuesday, February 21, 2023 4:13 PM
To: charleso/git-cc ***@***.***>
Subject: RE: [EXTERNAL] Re: [charleso/git-cc] Unable to initialize gitcc (Issue #101)

Hello Charleso ,

I installed  2.7.9 version of Python .I was able to eliminate that error.
Now I am getting below error.

$ gitcc rebase
No 'clearcase' variable found for branch 'master'


I want to rebase on main without any branches.I am using base clearcase.

This is my gitcc.file content

[core]
include = Import
exclude = lost+found
ignore_private_files = False
debug = False
type = Clearcase
[master]
clearcase = C:\Users\E9951943\E9951943_CC_Git\vobs\sandbox
branches = main

But still the issue persists. Please assist.

Regards,
Abubakar.M.K

From: charleso ***@***.******@***.***>>
Sent: Tuesday, February 21, 2023 4:05 PM
To: charleso/git-cc ***@***.******@***.***>>
Cc: Karajagi, Abubakar ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [charleso/git-cc] Unable to initialize gitcc (Issue #101)


I'm really sorry. This package is not really supported. It looks like we probably need to upgrade gitcc to support Python 3.11 but I'm afraid I'm unable to help with that. I just want to set expectations now so you don't waste your time. :(
