### ISSUE TITLE
/bin/env: python: No such file or directory

### ISSUE THREAD

**Issue by vikramsai458** [charleso/git-cc#34]
Hi

When i try to run any of the command, it is throwing me the below error.

/bin/env: python: No such file or directory

Actually I have downloaded git-cc repository as zip file and copied to my local machine. and then i try to run the commands mentioned below

$ "<local-path>/git-cc-master/gitcc" init D:/CC/View/CVOB.

Is there anything wrong in doing this. Can you please help me out in correcting it.

Note:- I have python also already installed in my local machine.

Thanks In advance..

Regards,
A.Vikramsai

**Comment by robbennett** [comment]
So I'm having the same problem I have python 2.7.10 installed on my computer. If I do the python gitcc init it gives me python: command not found. Any help would be nice.

**Comment by charleso** [comment]
@robbennett What OS are you running? I'm assuming `python` is on the `PATH` - eg if you type `python` from the command line it works? If this is windows are you running from `cygwin`/`msysgit`, or just the normal cmd shell?

**Comment by robbennett** [comment]
I'm running on windows, I'm using git bash she'll to do the commands in. What she'll should I be running on windows?

**Comment by charleso** [comment]
@robbennett git bash, as in `msysgit`? That's what I used to run. Can you run `python`? What happens if you run `python gitcc`?

**Comment by robbennett** [comment]
If I remember it said command not found

**Comment by charleso** [comment]
@robbennett You'll need to update `PATH` to include `python`.

**Comment by robbennett** [comment]
Oh ok well I guess I'll have to Google how to do that. I have no idea how.

**Comment by charleso** [comment]
@robbennett Yeah, sorry Rob, I can't really help you. I have to warn you `git-cc` is not friendly - it's not documented and will throws weird errors if anything goes slightly wrong. If I still used Clearcase (it's been > 5 years) I would give it a complete overhaul, but it's been too long. Best of luck. :(

**Comment by robbennett** [comment]
Ok so I got the path now I'm getting a new problem 
Traceback (most recent call last):
	File "c:/Users/RobBennett/Documents/git-cc-master/git-cc-master/gitcc:, line 4, in <module>
	import rebase, checkin, init, sync, reset, tag, update
	File "c:/Users/RobBennett/Documetns/git-cc-master/git-cc-master/rebase.py", line 7, in <module>
	from users import users, mailSuffix
	File "c:/Users/RobBennett/Documents/git-cc-master/git-cc-master/users.py", line 9
	include = Oracle package
	
SyntaxError: invalid syntax
