### ISSUE TITLE
gitcc fails on rebase

### ISSUE THREAD

**Issue by djraags** [charleso/git-cc#60]
Hi, 

While using gitcc rebase, i get this below error, Any idea what could cause this. 

> cleartool lsh -fmt %o%m|%Nd|%u|%En|%Vn|%Nc\n -recurse .
Traceback (most recent call last):
  File "../gitcc", line 48, in <module>
    main()
  File "../gitcc", line 14, in main
    return invoke(cmd, args)
  File "../gitcc", line 38, in invoke
    cmd.main(*args)
  File "h:\Tools\git-cc-master\git-cc-master\rebase.py", line 43, in main
    history = getHistory(since)
  File "h:\Tools\git-cc-master\git-cc-master\rebase.py", line 90, in getHistory
    return cc_exec(lsh)
  File "h:\Tools\git-cc-master\git-cc-master\common.py", line 50, in cc_exec
    return popen('cleartool', cmd, CC_DIR, **args)
  File "h:\Tools\git-cc-master\git-cc-master\common.py", line 62, in popen
    raise Exception(decodeString(encoding, stderr + stdout))
Exception: cleartool: Error: Not an object in a vob: ".".

Thanks,
Raghav

**Comment by hitenc** [comment]
It seesms gitcc is run against a  view-private file. Identify that file and remove. Then try again

**Comment by charleso** [comment]
@djraags What path did you specify on `git-cc init`? That's being used to run `cleartool lsh`, but it looks like you've used `.` which is incorrect - it should be an absolute path.

**Comment by djraags** [comment]
Charleso, i did give abs path. here is the snapshot of commands i have tried. 

KGF684@KGF684-02 /h/Tools/git-cc-master/git-cc-master
$ cd framework/

KGF684@KGF684-02 /h/Tools/git-cc-master/git-cc-master/framework
$ ls

KGF684@KGF684-02 /h/Tools/git-cc-master/git-cc-master/framework
$ git init
Initialized empty Git repository in h:/Tools/git-cc-master/git-cc-master/framewo
rk/.git/

KGF684@KGF684-02 /h/Tools/git-cc-master/git-cc-master/framework (master)
$ ../gitcc init /c/C
CC_Control/               CSR_uEnergy_SDK-2.4.3.26/ ca
CC_Snapshots/             Convert/                  cygwin/

KGF684@KGF684-02 /h/Tools/git-cc-master/git-cc-master/framework (master)
$ ../gitcc init /c/CC_Snapshots/KGF684_view9/
> git config core.autocrlf false

KGF684@KGF684-02 /h/Tools/git-cc-master/git-cc-master/framework (master)
$ ../gitcc rebase
> git ls-files --modified
> cleartool update
> git log -n 1 --pretty=format:%ai master_cc
> cleartool ls -recurse -short .
Traceback (most recent call last):
  File "../gitcc", line 48, in <module>
    main()
  File "../gitcc", line 14, in main
    return invoke(cmd, args)
  File "../gitcc", line 38, in invoke
    cmd.main(*args)
  File "h:\Tools\git-cc-master\git-cc-master\rebase.py", line 38, in main
    cache.start()
  File "h:\Tools\git-cc-master\git-cc-master\cache.py", line 22, in start
    self.initial()
  File "h:\Tools\git-cc-master\git-cc-master\cache.py", line 32, in initial
    self.read(cc_exec(ls))
  File "h:\Tools\git-cc-master\git-cc-master\common.py", line 50, in cc_exec
    return popen('cleartool', cmd, CC_DIR, **args)
  File "h:\Tools\git-cc-master\git-cc-master\common.py", line 62, in popen
    raise Exception(decodeString(encoding, stderr + stdout))
Exception: cleartool: Error: Pathname is not within a VOB: "."

**Comment by djraags** [comment]
@hitenc : I dont have any private files, even than i see this error.

**Comment by charleso** [comment]
@djraags Hmm. I might be mis-reading, but did you type `gitcc init` twice?

In any case what's in your `.gitcc` file under the `clearcase` flag? Try switching to that directory and running `cleartool lshistory` manually. That's all git-cc is trying to do, so I suspect something is wrong with the configuration.

**Comment by rohinigajawada** [comment]
Hi,

Did you complete the migration of CC to GIT using this.

Need help in migrating clearcase to GIT using this git-cc

~Roh

**Comment by amousa1968** [comment]
Yes I did and I scripted it in bash script.  Therefore you need few things to have before migration.  1- need to have the list of items of the configspec for the vob, then the elements, and Release tip labels. 

Run the script you will be able to migrate from CC to Git.  I am free to take on the next project to migrate if your company is looking for consultant.  Message me.
