### ISSUE TITLE
git-cc does not support python 53

### ISSUE THREAD

**Issue by amousa1968** [charleso/git-cc#73]
I have python 2.7, and python 35 installed on a window 7 64 bit.  
Migrating Clearcase Base snapshot to Git, and getting error when using gitcc rebase and gitcc update "initial commit" see errors 

$ gitcc update "Initial commit"
> cleartool update .
Traceback (most recent call last):
  File "C:\Python35-32\Scripts\gitcc-script.py", line 9, in <module>
    load_entry_point('git-cc==1.0.1.dev0', 'console_scripts', 'gitcc')()
  File "c:\python35-32\lib\site-packages\git_cc\gitcc.py", line 25, in main
    return invoke(cmd, args)
  File "c:\python35-32\lib\site-packages\git_cc\gitcc.py", line 50, in invoke
    cmd.main(*args)
  File "c:\python35-32\lib\site-packages\git_cc\update.py", line 11, in main
    cc_exec(['update', '.'], errors=False)
  File "c:\python35-32\lib\site-packages\git_cc\common.py", line 80, in cc_exec
    return popen('cleartool', cmd, CC_DIR, **args)
  File "c:\python35-32\lib\site-packages\git_cc\common.py", line 87, in popen
    pipe = Popen(cmd, cwd=cwd, stdout=PIPE, stderr=PIPE, env=env)
  File "c:\python35-32\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "c:\python35-32\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
**NotADirectoryError: [WinError 267] The directory name is invalid**
 
Does the program support Py2.7 or py3.4, or py3.5????  Please let me know what is missing and what is going on?   Thanks

**Comment by amousa1968** [comment]
Where do I need to set the directory for gitcc to understand the path.
