### ISSUE TITLE
git-cc fails in subprocess.py

### ISSUE THREAD

**Issue by weberjn** [charleso/git-cc#76]
Hi,

git-cc cannot start cleartool, I hacked subprocess.py to output the arguments, looks like executable is empty:

executable: None
args: git branch

$ gitcc init d:/snapshot/orbx2_int/middleware/orbx2
None
git branch
Traceback (most recent call last):
  File "D:\programme\Anaconda2\Scripts\gitcc-script.py", line 11, in <module>
    load_entry_point('git-cc==1.0.1.dev0', 'console_scripts', 'gitcc')()
  File "D:\programme\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 565, in load_entry_point
  File "D:\programme\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2598, in load_entry_point
  File "D:\programme\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2258, in load
  File "D:\programme\Anaconda2\lib\site-packages\setuptools-27.2.0-py2.7.egg\pkg_resources\__init__.py", line 2264, in resolve
  File "D:\programme\Anaconda2\lib\site-packages\git_cc\gitcc.py", line 7, in <module>
    from . import checkin
  File "D:\programme\Anaconda2\lib\site-packages\git_cc\checkin.py", line 3, in <module>
    from .common import *
  File "D:\programme\Anaconda2\lib\site-packages\git_cc\common.py", line 224, in <module>
    CURRENT_BRANCH = getCurrentBranch() or 'master'
  File "D:\programme\Anaconda2\lib\site-packages\git_cc\common.py", line 121, in getCurrentBranch
    for branch in git_exec(['branch']).split('\n'):
  File "D:\programme\Anaconda2\lib\site-packages\git_cc\common.py", line 77, in git_exec
    return popen('git', cmd, GIT_DIR, encoding='UTF-8', **args)
  File "D:\programme\Anaconda2\lib\site-packages\git_cc\common.py", line 87, in popen
    pipe = Popen(cmd, cwd=cwd, stdout=PIPE, stderr=PIPE, env=env)
  File "D:\programme\Anaconda2\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "D:\programme\Anaconda2\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden
[11:24:34] k263335@WS017634:/d/snapshot/orbx2_int/middleware/orbx2

**Comment by charleso** [comment]
@weberjn I'm afraid I won't be much help here. That said, that stacktrace look like it's running `git` not `cleartool`. Does that help?

```
File "D:\programme\Anaconda2\lib\site-packages\git_cc\common.py", line 77, in git_exec
return popen('git', cmd, GIT_DIR, encoding='UTF-8', **args)
```

**Comment by weberjn** [comment]
In the mean time I restarted with msys2 and its python2, now things look better. Also, I have git working dir in clearcase dir.
But still not there, yet ..

**Comment by weberjn** [comment]
OK, one problem was, that sys.platform == 'msys'
so FS was wrong.

Anyway, gitcc rebase terminates now without error, but result is not what I expected, a git repository with history.
There is no git history (there should be the Clearcase history of files, shouldn't it?) If I add . there is only the current files in the history.

I do not understand, where the git working directory should be, in the clearcase snapshot directory or in another place? For what is the clearcase = setting in gitcc if you have the parameter for init: gitcc init d:/view/xyz

gitcc checkin - checks in to Clearcase and not git, right?

**Comment by charleso** [comment]
@weberjn 

> There is no git history (there should be the Clearcase history of files, shouldn't it?) If I add . there is only the current files in the history.

What did the output look like? What do you mean by the "current files"? What do you get if you run `git log`?

I suspect it might be related to the branches. By default git-cc is using `main`. You should be able to have a look at the cached output of the `cleartool ls-history` command by opening the `.git/lshistory.bak`, and rerun the rebase again quickly without having to wait for the slowest part of the rebase which is fetching all the history.

```
gitcc rebase --load=.git/lshistory.bak
```

> where the git working directory should be, in the clearcase snapshot directory or in another place? 

The git directory is where you run the `gitcc` command - and it knows about the clearcase view which is elsewhere. (`d:/view/xyz` in your example).

> gitcc checkin - checks in to Clearcase and not git, right?

Sorry for the badly named commands. That should really be `gitcc push` or thereabouts. It's taking any changes in your local git repository and checking them in to clearcase.

**Comment by weberjn** [comment]
No, if it checks in to Clearcase, checkin is fine

Problem was the branches filter,

> \main\ORBX_2_INT\1 \
> [u'', u'main', u'ORBX_2_INT', u'1']
> ['main']
> if fnmatch(version, branch):

returned false, this is again a forward/backslash problem.

**Comment by charleso** [comment]
@weberjn Do you have git-cc working now? Can I close this issue?

**Comment by weberjn** [comment]
No, I have given up, I switched to SVNExporter, which worked for me.
