### ISSUE TITLE
Error during gitcc rebase

### ISSUE THREAD

**Issue by alicanhaman** [charleso/git-cc#88]
Hello, when running gitcc rebase, I keep getting the same error after some time. Then I am stuck in master_cc branch with nothing much to do. I am no expert on git or clearcase just trying to work this out, can you guide me on how to troubleshoot this error and rerun gitcc rebase from where it left off.

Trace: 
git rebase master_ci master_cc
Traceback (most recent call last):
  File "C:\Python27\Scripts\gitcc-script.py", line 11, in <module>
    load_entry_point('git-cc==1.0.1.dev0', 'console_scripts', 'gitcc')()
  File "c:\python27\lib\site-packages\git_cc\gitcc.py", line 25, in main
    return invoke(cmd, args)
  File "c:\python27\lib\site-packages\git_cc\gitcc.py", line 52, in invoke
    cmd.main(*args)
  File "c:\python27\lib\site-packages\git_cc\rebase.py", line 54, in main
    doStash(lambda: doCommit(cs), stash)
  File "c:\python27\lib\site-packages\git_cc\common.py", line 68, in doStash
    f()
  File "c:\python27\lib\site-packages\git_cc\rebase.py", line 54, in <lambda>
    doStash(lambda: doCommit(cs), stash)
  File "c:\python27\lib\site-packages\git_cc\rebase.py", line 68, in doCommit
    git_exec(['rebase', CI_TAG, CC_TAG])
  File "c:\python27\lib\site-packages\git_cc\common.py", line 77, in git_exec
    return popen('git', cmd, GIT_DIR, encoding='UTF-8', **args)
  File "c:\python27\lib\site-packages\git_cc\common.py", line 92, in popen
    raise Exception(decodeString(encoding, stderr + stdout))
Exception: Cannot rebase: You have unstaged changes.
Please commit or stash them.

**Comment by charleso** [comment]
@alicanhaman My apologies for my absolutely horrible code that I wrote all those years ago. :(

I think from memory the error you're seeing is masking the real one. Try removing the `finally:` here and see what error you really get.

https://github.com/charleso/git-cc/blob/master/git_cc/rebase.py#L66
